### ISSUE TITLE
Support for Ubuntu 19

### ISSUE THREAD

**Issue by mattburlage** [PierreGode/Linux-Active-Directory-join-script#10]
This script is a freaking life saver. I'd love to help get it working with Ubuntu 19. What can I do to help? Thanks.

**Comment by PierreGode** [comment]
Hi! 
Thank you! 

I Will do a quick overview of the 19 changes. 
If I don’t see any changes requiring any configuration changes then I can add Ubuntu 19 as supported OS on Monday. 
Due to lack of time I might need a tester, I could create a test branch and add you as reviewer if you have time to test it out on Ubuntu 19.
Best regards Pierre

**Comment by PierreGode** [comment]
Hi! the script has now Ubuntu 19 support.
I am closing this ticket.
Best Regards Pierre
